apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: docker.io/iteratec/teamdojo
      context: ../../../../TeamDojo
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
