apiVersion: v1
kind: Secret
metadata:
  name: teamdojo-postgresql
  namespace: teamdojo
  labels:
    app: teamdojo-postgresql
type: Opaque
data:
  postgresql-password: OTc2NzgxNDEzN2EzZjI0ODM0ODExYjJhZmUyZmQwOGMyYTBkOTE2ZmM2ZTFkMTRjYmFkNTg5YTMzNWQ5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamdojo-postgresql
  namespace: teamdojo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamdojo-postgresql
  template:
    metadata:
      labels:
        app: teamdojo-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:14.1
          env:
            - name: POSTGRES_USER
              value: teamDojo
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: teamdojo-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: teamdojo-postgresql
  namespace: teamdojo
spec:
  selector:
    app: teamdojo-postgresql
  ports:
    - port: 5432
