@startuml
' SPDX-FileCopyrightText: the TeamDojo authors
' SPDX-License-Identifier: Apache-2.0

skinparam shadowing false
skinparam componentStyle uml2

package com.iteratec.teamdojo.service {
    interface FooService {
        FooDTO save(FooDTO)
        Optional<FooDTO> partialUpdate(FooDTO)
        Page<FooDTO> findAll(Pageable)
        Optional<FooDTO> findOne(Long)
        void delete(Long)
    }

}

package com.iteratec.teamdojo.service.impl {
    class FooServiceImpl <<Service>>
}

package com.iteratec.teamdojo.service.impl.custom {
    class ExtendedFooServiceImpl <<Service,Primary>> {
        FooDTO save(FooDTO)
    }
}

FooServiceImpl .up.|> FooService
ExtendedFooServiceImpl -|> FooServiceImpl

@enduml
