/*
 SPDX-FileCopyrightText: the TeamDojo authors
 SPDX-License-Identifier: Apache-2.0
 */
package com.iteratec.teamdojo.service.mapper.custom;

import com.iteratec.teamdojo.domain.custom.TeamScore;
import com.iteratec.teamdojo.service.dto.custom.TeamScoreDTO;
import com.iteratec.teamdojo.service.mapper.EntityMapper;
import org.mapstruct.Mapper;

/**
 * Mapper for the entity {@link TeamScore} and its DTO {@link TeamScoreDTO}
 *
 * <p>This mapper is not generated by the JDL because the entity has no underlying database table and is pure synthetic
 * resulting from some join queries.</p>
 */
@Mapper(componentModel = "spring", uses = {})
public interface TeamScoreMapper extends EntityMapper<TeamScoreDTO, TeamScore> {}
