65,69d64
<     data:
<         web:
<             pageable:
<               default-page-size: 100000
<               max-page-size: 100000
90a86
> 
121,123d116
<     cache:
<      ehcache:
<         max-entries: 10000
147,149c140
< application:
<     mattermost: https://iterachat.iteratec.de/hooks/gpucc9dcg7fqfbyyb4i38pqgmh
<     frontend: http://localhost:9000/#/
---
> # application:
