apiVersion: v1
kind: Service
metadata:
  name: teamdojo
  namespace: teamdojo
  labels:
    app: teamdojo
spec:
  selector:
    app: teamdojo
  type: ClusterIP
  ports:
    - name: http
      port: 8080
