apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: teamdojo
  namespace: teamdojo
spec:
  rules:
    - host: teamdojo.teamdojo.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: teamdojo
              servicePort: 8080
