package com.iteratec.teamdojo.domain.custom;

import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import lombok.experimental.Accessors;

/**
 * This represents a skill which is achievable by a team
 *
 * <p>This domain entity is not generated by the JDL because this data is derived via SQL joins over some database
 * entities.</p>
 *
 * <p>In v1 they just used the companion DTO class in the repository, but this would breaks the architectural rule that
 * DTOs must not be used to exchange data between services and repositories.</p>
 */
@Getter
@Setter
@ToString
@AllArgsConstructor
@Accessors(chain = true)
public class AchievableSkill {

    private Long teamSkillId;
    private Long skillId;
    private String title;
    private String description;
    private Instant achievedAt;
    private Instant verifiedAt;
    private Integer vote;
    private String voters;
    private Boolean irrelevant;
    private Integer score;
    private Integer skillExpiryPeriod;
    private Double rateScore;
    private Integer rateCount;
}
